# Generated by Django 4.2.11 on 2025-12-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': []},
        ),
    ]
