# Generated by Django 4.2.11 on 2025-12-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_assign_developers', 'Can assign developers to a project')]},
        ),
    ]
