# Generated by Django 4.2.11 on 2025-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
