# Generated by Django 4.2.11 on 2025-10-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='skill',
        ),
        migrations.AddField(
            model_name='developer',
            name='skill',
            field=models.ManyToManyField(to='developers.skill'),
        ),
    ]
